### ISSUE TITLE
Import GMLAS bbox CRS

### ISSUE THREAD

**Issue by arnaud-morvan** [INSPIRE-MIF/gml_application_schema_toolbox#11]
This is a issue concerning the extent CRS handling in the import GMLAS tab.

We pass a bbox parameter in gdal.VectorTranslate.
I have tried to convert the bbox to the first layer CRS, but I do have not yet results for now with this method.

IMHO, it seems more robust to pass the bbox CRS to GDAL, as we are not sure that all layers and all geometries in GML file have the same SRS.

It seems that og2ogr support -spat_srs option that override the input bbox srs.
GDALVectorTranslate do not seems to have such option.

**Comment by rouault** [comment]
I've just added a spatSRS option : https://github.com/rouault/gdal2/commit/02d58a66fd3f287afb8dd5878aa1026c1e12e5c0

**Comment by arnaud-morvan** [comment]
Done in bc7a0afc51d4948e30be68e84cc456d0d07bd0e7
